apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    app: solid-builders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
